BAU - Fix `deployment_test.rb` wrong integer size
Description:
- https://github.com/alphagov/release/blob/main/test/unit/deployment_test.rb#L153 is failing in https://github.com/alphagov/release/actions/runs/24515940540/job/71659808805#step:8:112 because
```
RuntimeError: Neutered Exception ActiveModel::RangeError: 178237509603 is out of range for ActiveModel::Type::Integer with limit 4 bytes
```
- This is because `SecureRandom.hex(6))` is generating 6 bytes when the `id` column in MySQL has a limit of 4 bytes. So set this to `hex(4)` to stop the test from failing