Handle deployments without commits
It's possible that commits is equal to an empty array as this is how we handle Octokit::NotFound, causing

NoMethodError
undefined method 'sha' for nil (NoMethodError)

    commit_sha = commits.first.sha || ""
                              ^^^^

This uses safe navigation operator to handle those edge cases.