Handle deployments without commits on Deployment page
It's possible that commits is equal to an empty array as this is how we handle
Octokit::NotFound, causing:
   NoMethodError undefined method 'sha' for nil
   (NoMethodError)

https://govuk.sentry.io/issues/6896611471/events/f6885b88fd1f41348a52549bf2f30104/

This uses safe navigation operator to handle those edge cases.

Not adding a test as we are not testing views.