Upgrade capybara to get rails 5.x compatibility
This avoids the issue where certain form actions cause capybara to raise
a `NoMethodError` with the message `undefined method 'normalize_params'
for Rack::Utils:Module`.